config/routes.rb
Rails.application.routes.draw do

  resources :comments
  get 'user/edit'

  resources :exams
  get 'admin/index'

  devise_for :users
  root to: "home#index"
  resources :admin
  resources :events
  post "/users/edit" => "user#edit"

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :exam
end

app/models/event.rb
class Event < ActiveRecord::Base
end

app/models/exam.rb
class Exam < ActiveRecord::Base

  require 'carrierwave/orm/activerecord'
  has_many :comments
  belongs_to :student, class_name: "User", foreign_key: "student_id"
  belongs_to :professor, class_name: "User", foreign_key: "professor_id"
  mount_uploader :exam_picture, ExamPictureUploader
end

app/models/role.rb
class Role < ActiveRecord::Base
  has_many :users

  validates :name, presence: true
  validates :name, uniqueness: true
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  belongs_to :role
  validates_associated :role
  before_create :set_default_role
  has_many :exams

  def self.get_students
    User.joins(:role).where(roles: {name:'student'})
  end

  def is_registered
    if self.role.name == 'registered'
      return true
    elsif self.is_professor
      return true
    elsif self.is_student
      return true
    elsif self.is_admin
      return true
    else
      return false
    end
  end

  def is_professor
    if self.role.name == 'professor'
      return true
    else
      return false
    end
  end

  def is_student
    if self.role.name == 'student'
      return true
    else
      return false
    end
  end

  def is_admin
    if self.role.name == 'admin'
      return true
    else
      return false
    end
  end

  private
  def set_default_role
    self.role ||= Role.find_by_name('registered')
  end
end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
  def index

  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_comment, only: [:show, :edit, :update, :destroy]

  respond_to :html

  def index
    @comments = Comment.all
    respond_with(@comments)
  end

  def show
    respond_with(@comment)
  end

  def new
    @comment = Comment.new
    respond_with(@comment)
  end

  def edit
  end

  def create
    @comment = Comment.new(comment_params)
    @comment.save
    respond_with(@comment)
  end

  def update
    @comment.update(comment_params)
    respond_with(@comment)
  end

  def destroy
    @comment.destroy
    respond_with(@comment)
  end

  private
    def set_comment
      @comment = Comment.find(params[:id])
    end

    def comment_params
      params.require(:comment).permit(:text, :exam_id)
    end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController

  before_action :set_event, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!

  def index
    if current_user.is_registered
      @user = current_user
      @events = Event.all
    else
      render(json: {msg: 'not authorized'}, status: 401)
    end
  end

  def new
    if current_user.is_professor
      @event = Event.new
    else
      render(json: {msg: 'not authorized'}, status: 401)
    end
  end

  def create
    if current_user.is_professor
      @event = Event.new(event_params)
      @event.save
      redirect_to @event
    else
      render(json: {msg: 'not authorized'}, status: 401)
    end
  end

  def edit
    if current_user.is_professor
      @event = Event.find(params[:id])
    else
      render(json: {msg: 'not authorized'}, status: 401)
    end

  end

  def update
    if current_user.is_professor
      @event.update(event_params)
      redirect_to @event
    else
      render(json: {msg: 'not authorized'}, status: 401)
    end
  end


  def show
    @event = Event.find(params[:id])
  end

   def destroy
    if current_user.is_professor
      @event.destroy
      redirect_to events_path
    else
      render(json: {msg: 'not authorized'}, status: 401)
    end
  end

  private
  def set_event
    @event = Event.find(params[:id])
  end

  def event_params
    params.require(:event).permit(:title, :text, :start, :host, :location)
  end
end

app/controllers/exams_controller.rb
class ExamsController < ApplicationController
  before_action :set_exam, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: []
  respond_to :html

  def index

    @user = current_user
    if current_user.is_student
      @exams = Exam.where(student: current_user.id)
      render :index_student
    else
      @exams = Exam.where(professor: current_user.id)
      render :index_professor
    end
  end

  def show
    @comment = Comment.new
    respond_with(@exam)
  end

  def new
    if current_user.is_professor
      @exam = Exam.new
      @students_array = User.get_students.map { |student| [student.email, student.id] }
      respond_with(@exam)
    else
      render(json: {msg: 'not authorized'}, status: 401)
    end
  end

  def edit
    if current_user.is_professor
      @students_array = User.get_students.map { |student| [student.email, student.id] }
    else
      render(json: {msg: 'not authorized'}, status: 401)
    end
  end

  def create
    if current_user.is_professor
      requests_params = params[:exam]
      requests_params[:professor_id] = current_user.id
      @exam = Exam.new(exam_params)
      @exam.save
      respond_with(@exam)
    else
      render(json: {msg: 'not authorized'}, status: 401)
    end
  end

  def update
    if current_user.is_professor
      @exam.update(exam_params)
      respond_with(@exam)
    else
      render(json: {msg: 'not authorized'}, status: 401)
    end
  end

  def destroy
    if current_user.is_professor
      @exam.destroy
      respond_with(@exam)
    else
      render(json: {msg: 'not authorized'}, status: 401)
    end
  end

  private
  def set_exam
    @exam = Exam.find(params[:id])
  end

  def exam_params
    params.require(:exam).permit(:grade, :title, :exam_picture, :student_id, :professor_id)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def index

  end
end

app/controllers/user_controller.rb
class UserController < ApplicationController
  def edit
    if current_user.is_admin
      role_id = params[:post][:role]
      user_id = params[:user_id]

      user = User.find(user_id).update(role: Role.find(role_id))
    end
    redirect_to '/admin'
  end
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/exams_helper.rb
module ExamsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/admin/index.html.erb
<h1>AdminPanelDisplayListOverview:</h1>
<% if current_user.is_admin %>
<table>
  <% User.all.each do |user| %>
      <tr>
        <%= form_tag("/users/edit") do %>
            <td><%= user.email %></td>
            <%= hidden_field_tag("user_id", user.id) %>
            <td><%= select("post", "role", Role.all.collect { |role| [role.name, role.id] }, :selected => user.role.id) %></td>
            <td><%= submit_tag("Save") %></td>
        <% end %>
      </tr>
  <% end %>
</table>
<% else %>
<h1>Du kummst hier net rein</h1>
<% end %>

app/views/comments/_form.html.erb
<%= form_for(@comment,  url: comments_path) do |f| %>
    <% if @comment.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@comment.errors.count, "error") %> prohibited this comment from being saved:</h2>

          <ul>
            <% @comment.errors.full_messages.each do |message| %>
                <li><%= message %></li>
            <% end %>
          </ul>
        </div>
    <% end %>

    <div class="field">
      <%= f.label :text %><br>
      <%= f.text_field :text %>
      <%= f.hidden_field :exam_id, :value => @exam.id %>
    </div>
    <div class="actions">
      <%= f.submit %>
    </div>
<% end %>

app/views/comments/_index.html.erb
<h1>Listing comments</h1>

<table>
  <thead>
    <tr>
      <th>Text</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @comments.each do |comment| %>
      <tr>
        <td><%= comment.text %></td>
        <td><%= link_to 'Show', comment %></td>
        <td><%= link_to 'Edit', edit_comment_path(comment) %></td>
        <td><%= link_to 'Destroy', comment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Comment', new_comment_path %>

app/views/comments/_new.html.erb
<h1>New comment</h1>

<%= render 'comments/form', object: @comment %>

app/views/comments/_show.html.erb
<% @exam.comments.each  do |comment| %>
    <div style="background-color: #E0F2F7; margin-bottom: 10px;">
    <p id="notice"><%= notice %></p>

    <p>
      <strong>Kommentar vom <%= comment.created_at %>:</strong>
      <p><%= comment.text %></p>
    </p>
    </div>
<% end %>

app/views/comments/edit.html.erb
<h1>Editing comment</h1>

<%= render 'form' %>

<%= link_to 'Show', @comment %> |
<%= link_to 'Back', comments_path %>

app/views/comments/show.html.erb
    <div style="background-color: #E0F2F7; margin-bottom: 10px;">
    <p id="notice"><%= notice %></p>

    <p>
      <strong>Kommentar wurde erfolgreich erstellt!</strong>
      <p><a href="<%= exam_path(@comment.exam_id) %>">zur&uuml;ck zur Pr&uuml;fung</a></p>
    </p>
    </div>

app/views/events/_form.html.erb
<%= form_for(@event) do |f| %>
    <% if @event.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@event.errors.count, "error") %> prohibited this event from being saved:</h2>

          <ul>
            <% @event.errors.full_messages.each do |message| %>
                <li><%= message %></li>
            <% end %>
          </ul>
        </div>
    <% end %>

    <div class="field">
      <%= f.label :title %><br>
      <%= f.text_field :title %>
    </div>
    <div class="field">
      <%= f.label :start %><br>
      <%= f.datetime_field :start %>
    </div>
    <div class="field">
      <%= f.label :host %><br>
      <%= f.text_field :host %>
    </div>
    <div class="field">
      <%= f.label :location %><br>
      <%= f.text_field :location %>
    </div>
    <div class="field">
      <%= f.label :text %><br>
      <%= f.text_area :text %>
    </div>

    <div class="actions">
      <%= f.submit %>
    </div>
<% end %>

app/views/events/delete.html.erb
<h1>Events#delete</h1>
<p>Find me in app/views/events/delete.html.erb</p>

app/views/events/edit.html.erb
<h1>Edit Event</h1>

<%= render 'form' %>
<%= link_to 'Back', events_path %>

app/views/events/index.html.erb
<h1>Events</h1>
<p>
  Listing all Events
</p>
<% if current_user.is_professor %>
    <%= link_to 'New event', new_event_path %>
<% end %>
<table>
  <tr>
    <th>Title</th>
    <th>Start</th>
    <th>Location</th>
    <th>Host</th>

    <% if current_user.is_professor %>
    <th>Edit</th>
    <th>Delete</th>
    <% end %>
  </tr>

  <% @events.each do |event| %>
      <tr>
        <td><%= link_to event.title , event_path(event)%></td>
        <td><%= event.start %></td>
        <td><%= event.location %></td>
        <td><%= event.host %></td>

        <% if current_user.is_professor %>
        <td><%= link_to 'Edit', edit_event_path(event) %></td>
        <td><%= link_to 'Destroy', event_path(event),
                        method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <% end %>
      </tr>
  <% end %>
</table>

app/views/events/new.html.erb
<h1>New Event</h1>
<p>Create a new event</p>

<%= render 'form' %>

<%= link_to 'Back', events_path %>

app/views/events/show.html.erb
<h1><%= @event.title %></h1>
<p><strong>Start:</strong> <%= @event.start %></p>
<p><strong>Location:</strong> <%= @event.location %></p>
<p><strong>Host:</strong> <%= @event.host %></p>
<p><strong>Description:</strong> <%= simple_format h @event.text %></p>
<%= current_user.is_professor ? (link_to 'Edit', edit_event_path(@event)) : '' %>
<%= link_to 'Back', events_path %>

app/views/exams/_form.html.erb
<%= form_for(@exam) do |f| %>
    <% if @exam.errors.any? %>
        <div id="error_explanation">
            <h2><%= pluralize(@exam.errors.count, "error") %> prohibited this exam from being saved:</h2>

            <ul>
                <% @exam.errors.full_messages.each do |message| %>
                    <li><%= message %></li>
                <% end %>
            </ul>
        </div>
    <% end %>
    <div class="field">
        <%= f.select(:student_id, @students_array) %>
    </div>
    <div class="field">
        <%= f.label :title %><br>
        <%= f.text_field :title %>
    </div>
    <div class="field">
        <%= f.label :grade %><br>
        <%= f.text_field :grade %>
    </div>
    <div class="field">
        <%= f.label :exam_picture%><br>
        <%= f.file_field :exam_picture, id: "file-upload" %>
    </div>
    <div class="actions">
        <%= f.submit %>
    </div>
<% end %>

app/views/exams/edit.html.erb
<h1>Editing exam</h1>

<%= render 'form' %>

<%= link_to 'Show', @exam %> |
<%= link_to 'Back', exams_path %>

app/views/exams/index_professor.html.erb
<h1><%= @user.email %></h1>

<table>
  <thead>
    <tr>
      <th>Grade</th>
	  <th>Title</th>
	  <th>Student</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @exams.each do |exam| %>
      <tr>
        <td><%= exam.grade %></td>
        <td><%= exam.title %></td>
        <td><%= exam.student.email %></td>
        <td><%= link_to 'Show', exam %></td>
        <td><%= link_to 'Edit', edit_exam_path(exam) %></td>
        <td><%= link_to 'Destroy', exam, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Exam', new_exam_path %>

app/views/exams/index_student.erb
<h1>E-Mail: <%= @user.email %></h1>

<table>
  <thead>
    <tr>
      <th>Note</th>
	  <th>Titel</th>
	  <th>Professor</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @exams.each do |exam| %>
      <tr>
        <td><%= exam.grade %></td>
        <td><%= exam.title %></td>
        <td><%= exam.professor.email %></td>
        <td><%= link_to 'Anzeigen', exam %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/exams/new.html.erb
<h1>New exam</h1>

<%= render 'form' %>

<%= link_to 'Back', exams_path %>

app/views/exams/show.html.erb
<p id="notice"><%= notice %></p>
<h1>Pruefung</h1>
<p>
  <strong>Note:</strong>
  <%= @exam.grade %>
</p>

<p>
  <strong>Titel:</strong>
  <%= @exam.title %>
</p>

<p>
  <img src="<%= @exam.exam_picture %>" />
</p>

<%= link_to 'Edit', edit_exam_path(@exam) %> |
<%= link_to 'Back', exams_path %>

<%= render partial: 'comments/show', object: @exam %>
<%= render partial: 'comments/new', object: @comment %>

app/views/home/index.erb
<h1>INDEX !!</h1>
<% if current_user.present? && current_user.is_registered %>
<%= link_to 'Events', events_path %>
</br>
<%= link_to 'Exams', exams_path %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>SoSi14</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag  :defaults %>
  <%= csrf_meta_tags %>
</head>
<body>




<% if user_signed_in? %>
    <%= link_to "Home", root_path %>
    <%= link_to "Sign out", destroy_user_session_path, :method => :delete %>
    <% if current_user.is_admin %>
        <%= link_to "Admin", :controller => :admin, :action => :index %>
    <% end %>
<% else %>
    <%= link_to "Sign in", new_user_session_path, :method => :get %>
    <%= link_to "Register", new_user_registration_path, :method => :get %>
<% end %>
<p class="notice"><%= notice %></p>
<p class="alert"><%= alert %></p>
<%= yield %>

</body>
</html>

app/views/user/edit.html.erb
<h1>User#edit</h1>
<p>Find me in app/views/user/edit.html.erb</p>